inputFilePatterns:
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2012-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2013-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2014-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2015-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2016-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2017-*-*/*-of-*"
knownFishingMMSIs: "../../treniformis/treniformis/_assets/GFW/FISHING_MMSI/KNOWN_AND_LIKELY/ANY_YEAR.txt"
anchoragesRootPath: "gs://world-fishing-827/data-production/classification/release-0.1.0/pipeline/output"
minRequiredPositions: 100
encounterMinHours: 3
encounterMaxKilometers: 1.0
