inputFilePatterns:
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2016-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2017-*-*/*-of-*"
  - "gs://world-fishing-827/scratch/timh/KKP_Indonesia_for_encounters_*.json"  
knownFishingMMSIs: "../../treniformis/treniformis/_assets/GFW/FISHING_MMSI/KNOWN_AND_LIKELY/ANY_YEAR.txt"
anchoragesRootPath: "gs://world-fishing-827/data-production/classification/release-0.1.0/pipeline/output"
minRequiredPositions: 3
encounterMinHours: 3
encounterMaxKilometers: 1.0
