inputFilePatterns:
  - "gs://benthos-pipeline/data-production-740/measures-pipeline/st-segment/2014-*-*/*-of-*"
knownFishingMMSIs: "../../treniformis/treniformis/_assets/GFW/FISHING_MMSI/KNOWN_AND_LIKELY/2014.txt"
jsonAnnotations:
  - inputFilePattern: "gs://world-fishing-827/data-production/classification/paper_prep/models/prod.fishing_range_classification/fishing_det_all.json.gz"
    timeRangeFieldName: "fishing_localisation"
    outputFieldName: "measure_new_score"
    defaultValue: 1.0
