inputFilePatterns:
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-01-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-02-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-03-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-04-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-05-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-06-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-07-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-08-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-09-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-10-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-11-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-12-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-01-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-02-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-03-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-04-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-05-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-06-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-07-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-08-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-09-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-10-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-11-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-12-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-01-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-02-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-03-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-04-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-05-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-06-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-07-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-08-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-09-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-10-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-11-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-12-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-01-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-02-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-03-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-04-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-05-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-06-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-07-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-08-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-09-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-10-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-11-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-12-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-01-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-02-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-03-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-04-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-05-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-06-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-07-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-08-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-09-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-10-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-11-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-12-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2017-01-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2017-02-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2017-03-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2017-04-*/*-of-*
  - gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2017-05-*/*-of-*
knownFishingMMSIs: "known_likely_suspected_and_reefers.txt"
jsonAnnotations:
  - inputFilePattern: "gs://world-fishing-827/data-production/classification/vessels_gear.json.gz"
    timeRangeFieldName: "fishing_localisation"
    outputFieldName: "nnet_score"
    defaultValue: 1.0
