inputFilePatterns:
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2012-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2013-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2014-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2015-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2016-*-*/*-of-*"
  - "gs://benthos-pipeline/data-production-740/classify-pipeline/classify-logistic/2017-*-*/*-of-*"
knownFishingMMSIs: "../../treniformis/treniformis/_assets/GFW/FISHING_MMSI/KNOWN_AND_LIKELY/ANY_YEAR.txt"
jsonAnnotations:
  - inputFilePattern: "gs://world-fishing-827/data-production/classification/paper_03_22/fishing_paper_unbroken.json.gz"
    timeRangeFieldName: "fishing_localisation"
    outputFieldName: "nnet_score"
    defaultValue: 1.0
