inputFilePatterns:
  # - "gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2012-*-*/*-of-*"
  # - "gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2013-*-*/*-of-*"
  - "gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2014-*-*/*-of-*"
  - "gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2015-*-*/*-of-*"
  # - "gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2016-*-*/*-of-*"
  # - "gs://p_p429_resampling_2/data-production/classify-pipeline/classify/2017-*-*/*-of-*"
knownFishingMMSIs: "known_likely_suspected_and_reefers.txt"
jsonAnnotations:
  - inputFilePattern: "gs://world-fishing-827/data-production/classification/vessels_gear.json.gz"
    timeRangeFieldName: "fishing_localisation"
    outputFieldName: "nnet_score"
    defaultValue: 1.0
