inputFilePatterns:
  - "gs://p_p429_resampling_3/data-production/classify-pipeline/classify/2012-*-*/*-of-*"
  - "gs://p_p429_resampling_3/data-production/classify-pipeline/classify/2013-*-*/*-of-*"
  - "gs://p_p429_resampling_3/data-production/classify-pipeline/classify/2014-*-*/*-of-*"
  - "gs://p_p429_resampling_3/data-production/classify-pipeline/classify/2015-*-*/*-of-*"
  - "gs://p_p429_resampling_3/data-production/classify-pipeline/classify/2016-*-*/*-of-*"
  - "gs://p_p429_resampling_3/data-production/classify-pipeline/classify/2017-*-*/*-of-*"
knownFishingMMSIs: "../../treniformis/treniformis/_assets/GFW/FISHING_MMSI/KNOWN_LIKELY_AND_SUSPECTED/ANY_YEAR.txt"
jsonAnnotations:
  - inputFilePattern: "gs://world-fishing-827/data-production/classification/paper_04_02/fishing_04_02.json.gz"
    timeRangeFieldName: "fishing_localisation"
    outputFieldName: "nnet_score"
    defaultValue: 1.0
