sudo: required
dist: trusty

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - sudo pip install tensorflow
  - sudo pip install google-api-python-client pyyaml python-dateutil NewlineJSON pytz yattag

script:
  - ./test_all
