#!/bin/bash

set -e

# Run scala dataflow pipeline tests.
#pushd pipeline
#sbt test
#popd

# Run python TF tests.
pushd classification
export TF_CPP_MIN_LOG_LEVEL=2
python -m compute_metrics_test
python -m classification.utility_test
python -m classification.objectives_test
python -m classification.models.models_test
python -m classification.file_iterator_test
popd

# Build docker containers
# docker build -f deployment/Dockerfile .
