#!/bin/bash

set -e

# Run python TF tests.
export TF_CPP_MIN_LOG_LEVEL=2
python -m train.compute_metrics_test
python -m classification.utility_test
python -m classification.objectives_test
python -m classification.models.models_test

