apiVersion: batch/v1
kind: Job
metadata:
  name: vessel-classification-inference
spec:
  template:
    metadata:
      name: vessel-classification-inference
    spec:
      containers:
      - name: vessel-classification-inference
        image: vessel-classification-inference
        command: ["python", "-m", "classification.run_inference",
          "alex.vessel_classification", "--unclassified_feature_path",
          "gs://alex-dataflow-scratch/features-scratch/20161004T144858Z/*.tfrecord",
          "--model_checkpoint_path",
          "gs://world-fishing-827/scratch/classification/alex.vessel_classification/alex_vessel_classification_161005_142034/model.ckpt-469115",
          "--inference_parallelism", "2",
          "--inference_results_path=tmp/infered_labels.txt"]
      restartPolicy: Never